name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo string
        run: echo "Hello World"
      - name: Multiline script
        run: |
          node -v
          npm -v
      - name: Python Command
        shell: python
        run: |
          import platform
          print(platform.processor())
  
  run-windows-commands:
    runs-on: windows-latest
    needs: [run-shell-commands]
    steps:
      - name: Directory Powershell
        run: Get-Location
      - name: Directory Bash
        shell: bash
        run: pwd
  
  run-python-commands:
    runs-on: ubuntu-latest
    needs: [run-windows-commands]
    steps:
      - name: Print Hello World
        shell: python
        run: print("Hello World")